Findev/feat/adding njwt
FinDevUnisinos/FinDev-backend pull request #4
Opened 2019-09-18 14:45 UTC by GIANUNISINOS

feats:

- Insert a user
- get a user by email
- generate token using njtw
- hashing the password to persist and compare
- receiving requires by JSON on body 

fix: 

- ajusts on connection

2019-09-20 18:11 UTC, joicecg requested changes

2019-09-20 18:11 UTC, joicecg commented on src/index.ts
> +/* ONLY FOR TESTS of token verify
Remove the comments.

2019-09-20 18:11 UTC, joicecg commented on src/index.ts
> +      let uc= new UserController
Use a more meaningful name.

2019-09-20 18:11 UTC, joicecg commented on src/index.ts
> +          res.send("User Inserted on Database")
Change to `User successfully created`

2019-09-20 18:11 UTC, joicecg commented on src/index.ts
> +    res.send("User Doesn't Inserted on Database")
Change to `failed to create user`

2019-09-20 18:31 UTC, GIANUNISINOS commented on src/index.ts
> +/* ONLY FOR TESTS of token verify
removing all comments on index.ts

2019-09-20 18:34 UTC, GIANUNISINOS commented on src/index.ts
> +      let uc= new UserController
changing to userController

2019-09-20 18:34 UTC, GIANUNISINOS commented on src/index.ts
> +          res.send("User Inserted on Database")
changing...

2019-09-20 18:35 UTC, GIANUNISINOS commented on src/index.ts
> +    res.send("User Doesn't Inserted on Database")
ok

2019-09-21 01:09 UTC, joicecg approved these changes

2019-09-21 01:09 UTC, merged