adding Skill, Worker and Interest on Projects
FinDevUnisinos/FinDev-backend pull request #6
Opened 2019-10-01 02:23 UTC by GIANUNISINOS

New feats:

- add Skill on a Project
- add Worker on a Project
- add Interest on a Project

2019-10-14 00:27 UTC, GIANUNISINOS commented
Como a Rosemary sugeriu... coloquei o level da skill nos relacionamentos N para N de projetos com habilidades e usuários com habilidades...

No momento para testar tem que colocar o nome do scheme no .env com "onlyDevelopment", mas depois que essa pull subir para master adequo o schema "findev"

2019-10-20 21:40 UTC, PedroBohlmann requested changes
Acho que vale a pena colocar alguns espaços dentro dos métodos, achei bastante apertado dificultando um pouco a leitura. Pode ser uma coisa minha.

2019-10-20 21:40 UTC, PedroBCSilva commented on src/api/ProjectAPI.ts
> +            const userId = user.id
Minha opnião poderia colocar alguns espaços aqui, tudo bastante colado

2019-10-20 21:40 UTC, PedroBCSilva commented on src/api/ProjectAPI.ts
> +            const level = Number.parseInt(req.body.level)
Mesma coisa que comentei antes sobre espaço

2019-10-20 22:01 UTC, GIANUNISINOS commented on src/api/ProjectAPI.ts
> +            const userId = user.id
fiz um refactor meio geral no arquivo colocando espaços

2019-10-20 22:01 UTC, GIANUNISINOS commented on src/api/ProjectAPI.ts
> +            const level = Number.parseInt(req.body.level)
fiz um refactor meio geral no arquivo colocando espaços

2019-10-20 22:20 UTC, PedroBohlmann approved these changes

2019-10-20 23:27 UTC, merged